<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Version>$(SLAssemblyVersion)</Version>
    <InformationalVersion>$(SLVersion)</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BunLabs.NAudio.Flac" Version="2.0.1" />
    <PackageReference Include="Concentus.Oggfile" Version="1.0.7" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="14.2.1.102" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.macOS" Version="14.2.1.102" />
    <PackageReference Include="HaroohieClub.NitroPacker" Version="3.3.5" />
    <PackageReference Include="HaruhiChokuretsuLib" Version="0.56.0" />
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
    <PackageReference Include="NLayer" Version="3.0.0" />
    <PackageReference Include="NLayer.NAudioSupport" Version="3.0.0" />
    <PackageReference Include="QuikGraph" Version="2.5.0" />
    <PackageReference Include="ReactiveUI" Version="24.1.0" />
    <PackageReference Include="ReactiveUI.SourceGenerators" Version="3.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Topten.RichTextKit" Version="0.4.167" />
    <PackageReference Include="VCDiff" Version="5.0.0" />
    <PackageReference Include="VGAudio" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Sources\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="MapIcons\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Defaults\DefaultCharacters.en.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Defaults\DefaultCharacters.ja.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="DefaultCharacters.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Defaults\DefaultFlags.en-US.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Defaults\DefaultNames.en-US.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
