trigger:
- none
pr:
- main

variables:
  - group: SerialLoopsPublic

jobs:
- job:
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
        platformName: 'Gtk'
      macOS:
        imageName: 'macOS-latest'
        platformName: 'Mac'
      Windows:
        imageName: 'windows-latest'
        platformName: 'Wpf'
  displayName: Build & Test
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    clean: true
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(Build.SourcesDirectory)/src/SerialLoops.$(platformName)/SerialLoops.$(platformName).csproj
    displayName: Build solution

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(Build.SourcesDirectory)/test/SerialLoops.Tests/SerialLoops.Tests.csproj
      publishTestResults: true
    displayName: Run tests
- job:
  displayName: UI Tests (Windows)
  pool:
    name: LoopyPool
    demands:
      - Agent.OS -equals Windows_NT
  steps:
  - checkout: self
    clean: publishTestResults
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(Build.SourcesDirectory)/test/ui/SerialLoops.Wpf.Tests/SerialLoops.Wpf.Tests.csproj
    displayName: Build SerialLoops.Wpf.Tests
  - task: Docker@2
    displayName: Pull devkitpro/devkitarm in advance
    inputs:
      command: pull
      arguments: devkitpro/devkitarm
  - task: WinAppDriver.winappdriver-pipelines-task.winappdriver-pipelines-task.Windows Application Driver@0
    displayName: 'Start WinAppDriver'
    inputs:
      WADArguments: '127.0.0.1:4723'
  - task: VSTest@3
    displayName: 'VsTest - Run UI Tests'
    inputs:
      testAssemblyVer2: |
        **\*SerialLoops.Wpf.Tests.dll
      uiTests: true
    env:
      APP_LOCATION: $(Build.SourcesDirectory)/src/SerialLoops.Wpf/bin/Debug/net8.0/SerialLoops.exe
      PROJECT_NAME: WinUITest
      ROM_URI: $(ChokuRomUri)
  - task: WinAppDriver.winappdriver-pipelines-task.winappdriver-pipelines-task.Windows Application Driver@0
    displayName: 'Close WinAppDriver'
    inputs:
      OperationType: Stop
    condition: always()
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/SerialLoops.log
      ArtifactName: SerialLoops_Logs
      publishLocation: Container
    displayName: Publish Serial Loops logs