trigger:
- none
pr:
- main

variables:
  - group: SerialLoopsPublic

jobs:
- job:
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
        platformName: 'Gtk'
      macOS:
        imageName: 'macOS-latest'
        platformName: 'Mac'
      Windows:
        imageName: 'windows-latest'
        platformName: 'Wpf'
  displayName: Build & Test
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    clean: true
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(Build.SourcesDirectory)/src/SerialLoops.$(platformName)/SerialLoops.$(platformName).csproj
    displayName: Build solution

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(Build.SourcesDirectory)/test/SerialLoops.Tests/SerialLoops.Tests.csproj
      publishTestResults: true
    displayName: Run tests
- job:
  displayName: UI Tests (Windows)
  pool:
    name: LoopyPool
    demands:
      - Agent.OS -equals Windows_NT
  steps:
  - checkout: self
    clean: publishTestResults
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(Build.SourcesDirectory)/src/SerialLoops.Wpf/SerialLoops.Wpf.csproj
    displayName: Build SerialLoops.Wpf
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(Build.SourcesDirectory)/test/ui/SerialLoops.Wpf.Tests/SerialLoops.Wpf.Tests.csproj
    displayName: Build SerialLoops.Wpf.Tests
  - task: Docker@2
    displayName: Pull devkitpro/devkitarm in advance
    inputs:
      command: pull
      arguments: devkitpro/devkitarm
  - task: ms-autotest.screen-resolution-utility-task.screen-resolution-utlity-task.ScreenResolutionUtility@1
    displayName: 'Set Screen Resolution'
    inputs:
      displaySettings: specific
      width: 3840
      height: 2160
  - task: VSTest@3
    displayName: 'VsTest - Run UI Tests'
    inputs:
      testAssemblyVer2: |
        **\*SerialLoops.Wpf.Tests.dll
        !**\obj\**
      uiTests: true
    env:
      APP_LOCATION: $(Build.SourcesDirectory)\src\SerialLoops.Wpf\bin\Debug\net8.0-windows\SerialLoops.exe
      PROJECT_NAME: WinUITest
      WINAPPDRIVER_LOC: 'C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe'
      ROM_URI: $(ChokuRomUri)
      LOG_FILE: $(Build.ArtifactStagingDirectory)/TestConsole.log
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/SerialLoops.log
      ArtifactName: SerialLoops_Logs
      publishLocation: Container
    displayName: Publish Serial Loops logs
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/TestConsole.log
      ArtifactName: ConsoleLogs
      publishLocation: Container
    displayName: Publish console logs
    condition: always()