trigger:
- none
pr:
- main

jobs:
- job:
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
        platformName: 'Gtk'
      macOS:
        imageName: 'macOS-latest'
        platformName: 'Mac'
      Windows:
        imageName: 'windows-latest'
        platformName: 'Wpf'
  displayName: Build & Test
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    clean: true
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(Build.SourcesDirectory)/src/SerialLoops.$(platformName)/SerialLoops.$(platformName).csproj
    displayName: Build solution

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(Build.SourcesDirectory)/test/SerialLoops.Tests/SerialLoops.Tests.csproj
      publishTestResults: true
    displayName: Run tests

