trigger:
- none
pr:
- main
- Avalonia

variables:
  - group: SerialLoopsPublic

jobs:
- job:
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
        targetFramework: 'net8.0'
      macOS:
        imageName: 'macOS-latest'
        targetFramework: 'net8.0'
      Windows:
        imageName: 'windows-latest'
        targetFramework: 'net8.0-windows'
  displayName: Build & Maybe Test
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    clean: true

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(Build.SourcesDirectory)/src/SerialLoops/SerialLoops.csproj
      arguments: -f $(targetFramework)
    displayName: Build project

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(Build.SourcesDirectory)/test/SerialLoops.Tests.Headless/SerialLoops.Tests.Headless.csproj
      arguments: -f $(targetFramework) --filter "Name !~ BackgroundMusicEditor_ReplacementAndRestoreWork"
      publishTestResults: true
    displayName: Run tests
    condition: eq(variables.imageName, 'windows-latest')
