trigger:
- none
pr:
- main
- Avalonia

variables:
  - group: SerialLoopsPublic

jobs:
- job:
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
        targetFramework: 'net8.0'
      macOS:
        imageName: 'macOS-latest'
        targetFramework: 'net8.0'
      Windows:
        imageName: 'windows-latest'
        targetFramework: 'net8.0-windows'
  displayName: Build & Test
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    clean: true

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(Build.SourcesDirectory)/src/SerialLoops/SerialLoops.csproj
      arguments: -f $(targetFramework)
    displayName: Build project
