trigger:
- none
pr:
- main

variables:
  - group: SerialLoopsPublic

jobs:
- job:
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
        platformName: 'Gtk'
      macOS:
        imageName: 'macOS-latest'
        platformName: 'Mac'
      Windows:
        imageName: 'windows-latest'
        platformName: 'Wpf'
  displayName: Build & Test
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    clean: true
    
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(Build.SourcesDirectory)/src/SerialLoops.$(platformName)/SerialLoops.$(platformName).csproj
    displayName: Build solution

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: $(Build.SourcesDirectory)/test/SerialLoops.Tests/SerialLoops.Tests.csproj
      publishTestResults: true
    displayName: Run tests
- job:
  displayName: UI Tests (Windows)
  pool:
    name: LoopyPool
    demands:
      - Agent.OS -equals Windows_NT
  steps:
  - checkout: self
    clean: publishTestResults
  - task: Docker@2
    displayName: Stat Docker
    inputs:
      command: ps
  - pwsh: |
      Get-ChildItem -Path C:\ -Recurse -Filter *docker*
      # taskkill /IM "dockerd.exe" /F
      # $dockerSettings = Get-Content $env:APPDATA\Docker\settings.json | ConvertFrom-Json
      # $dockerSettings.wslEngineEnabled = $True
      # Set-Content -Path $env:APPDATA\DOCKER\settings.json -Value $(ConvertTo-Json $dockerSettings)
      # & 'C:\Windows\system32\dockerd.exe'
    displayName: Switch Docker to Linux-based containers
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: $(Build.SourcesDirectory)/src/SerialLoops.Wpf/SerialLoops.Wpf.csproj
    displayName: Build SerialLoops.Wpf
  - task: Docker@2
    displayName: Pull devkitpro/devkitarm in advance
    inputs:
      command: pull
      arguments: devkitpro/devkitarm
  - task: WinAppDriver.winappdriver-pipelines-task.winappdriver-pipelines-task.Windows Application Driver@0
    displayName: 'Start WinAppDriver'
  - task: VSTest@3
    displayName: 'VsTest - Run UI Tests'
    inputs:
      testAssemblyVer2: |
        **\*Tests.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(Build.SourcesDirectory)/test/ui/SerialLoops.Wpf.Tests'
      uiTests: true
    env:
      APP_LOCATION: $(Build.SourcesDirectory)/src/SerialLoops.Wpf/bin/Debug/net8.0/SerialLoops.exe
      PROJECT_NAME: WinUITest
      ROM_URI: $(ChokuRomUri)
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactsStagingDirectory)/SerialLoops.log'
      ArtifactName: 'SerialLoops_Logs'
      publishLocation: 'Container'
    displayName: Publish Serial Loops logs