<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
    <Nullable>disable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Version>$(SLAssemblyVersion)</Version>
    <InformationalVersion>$(SLVersion)</InformationalVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <ApplicationIcon>Assets\serial-loops.ico</ApplicationIcon>
  </PropertyGroup>

  <Target Name="PreBuildSDL" BeforeTargets="PreBuildEvent" Condition="$([System.OperatingSystem]::IsMacOS()) And !Exists('libSDL2.dylib') And '$(CIBuild)' != 'true'">
    <Exec Command="/bin/bash -C install-sdl-macos.sh ../src/SerialLoops/libSDL2.dylib" WorkingDirectory="../.."/>
  </Target>
  <ItemGroup Condition="$([System.OperatingSystem]::IsMacOS())">
    <None Include="libSDL2.dylib">
      <TargetPath>runtimes/osx/native/libSDL2.dylib</TargetPath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="libSDL2.dylib">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <Target Name="PreBuildSTH" BeforeTargets="PreBuildEvent" Condition="'$(RuntimeIdentifier)' != ''">
    <Exec Command="dotnet publish submodules/NitroPacker.SymTableHelper/HaroohieClub.NitroPacker.SymTableHelper.csproj -c Release -f net10.0 -r $(RuntimeIdentifier) --self-contained /p:DebugType=None /p:DebugSymbols=false" WorkingDirectory="../.."/>
  </Target>
  <ItemGroup>
    <None Condition="'$(RuntimeIdentifier)' != '' And $([System.OperatingSystem]::IsWindows())" Include="..\..\submodules\NitroPacker.SymTableHelper\bin\Release\net10.0\$(RuntimeIdentifier)\publish\NitroPacker.SymTableHelper.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </None>
    <None Condition="'$(RuntimeIdentifier)' != '' And !$([System.OperatingSystem]::IsWindows())" Include="..\..\submodules\NitroPacker.SymTableHelper\bin\Release\net10.0\$(RuntimeIdentifier)\publish\NitroPacker.SymTableHelper">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <CFBundleName>Serial Loops</CFBundleName>
    <CFBundleDisplayName>Serial Loops</CFBundleDisplayName>
    <CFBundleIdentifier>club.haroohie.SerialLoops</CFBundleIdentifier>
    <CFBundleVersion>$(SLAssemblyVersion)</CFBundleVersion>
    <CFBundleShortVersionString>$(SLVersion)</CFBundleShortVersionString>
    <CFBundlePackageType>APPL</CFBundlePackageType>
    <CFBundleExecutable>SerialLoops</CFBundleExecutable>
    <CFBundleIconFile>SerialLoops.icns</CFBundleIconFile>
    <!-- Will be copied from output directory -->
    <NSPrincipalClass>NSApplication</NSPrincipalClass>
    <NSHighResolutionCapable>true</NSHighResolutionCapable>
  </PropertyGroup>

  <ItemGroup>
    <CFBundleDocumentTypes Include="slproj">
      <CFBundleTypeName>Serial Loops Project</CFBundleTypeName>
      <CFBundleTypeExtensions>slproj</CFBundleTypeExtensions>
      <CFBundleTypeRole>Editor</CFBundleTypeRole>
    </CFBundleDocumentTypes>
    <CFBundleDocumentTypes Include="slzip">
      <CFBundleTypeName>Serial Loops Exported Project</CFBundleTypeName>
      <CFBundleTypeExtensions>slzip</CFBundleTypeExtensions>
      <CFBundleTypeRole>Viewer</CFBundleTypeRole>
    </CFBundleDocumentTypes>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SerialLoops.Tests.Headless" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Remove="Assets\Strings.de.resx" />
    <AvaloniaResource Remove="Assets\Strings.en-GB.resx" />
    <AvaloniaResource Remove="Assets\Strings.es.resx" />
    <AvaloniaResource Remove="Assets\Strings.it.resx" />
    <AvaloniaResource Remove="Assets\Strings.ja.resx" />
    <AvaloniaResource Remove="Assets\Strings.pt-BR.resx" />
    <AvaloniaResource Remove="Assets\Strings.resx" />
    <AvaloniaResource Remove="Assets\Strings.ru.resx" />
    <AvaloniaResource Remove="Assets\Strings.zh-Hans.resx" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\MacIcon.icns" />
    <None Remove="Assets\serial-loops.ico" />
    <None Remove="Views\Editors\ScriptCommandEditors\HaruhiMeterScriptCommandEditorView.axaml~" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
    <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
    <PackageReference Include="Avalonia.Controls.Markdown" Version="12.2.3" />
    <PackageReference Include="Avalonia.Controls.PanAndZoom" Version="11.3.0" />
    <PackageReference Include="Avalonia.Controls.TreeDataGrid" Version="12.2.1" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Labs.Controls" Version="12.0.2" />
    <PackageReference Include="Avalonia.Labs.Panels" Version="12.0.2" />
    <PackageReference Include="Avalonia.Skia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.4" />
    <!--The behaviors packages past 11.1.0.4 break our middle click to close functionality, so we're staying on that package for now.-->
    <PackageReference Include="DialogHost.Avalonia" Version="0.12.3" />
    <PackageReference Include="Emik.Rubbish" Version="1.1.0" />
    <PackageReference Include="HaroohieClub.DotNet.Bundle" Version="1.0.3" />
    <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
    <PackageReference Include="MiniToolbar.Avalonia" Version="2.0.0.7" />
    <PackageReference Include="ReactiveHistory" Version="0.10.7" />
    <PackageReference Include="ReactiveUI" Version="24.2.0" />
    <PackageReference Include="ReactiveUI.Avalonia" Version="12.1.1" />
    <PackageReference Include="ReactiveUI.SourceGenerators" Version="3.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SixLabors.Fonts" Version="2.1.3" />
    <PackageReference Include="Svg.Controls.Avalonia" Version="12.0.0.17" />
    <PackageReference Include="Tabalonia" Version="12.0.0" />
    <PackageReference Include="Xaml.Behaviors.Avalonia" Version="12.0.7" />
  </ItemGroup>
  
  <ItemGroup>
    <AvaloniaUILicenseKey Include="avln_on_key:v1:4d99629b51b147a2ac2f592f9915c234" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net10.0-windows'">
    <PackageReference Include="NAudio.Sdl2" Version="2.2.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Condition="'$(RuntimeIdentifier)' == ''" Include="..\..\submodules\NitroPacker.SymTableHelper\HaroohieClub.NitroPacker.SymTableHelper.csproj" />
    <ProjectReference Include="..\SerialLoops.Lib\SerialLoops.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\SoundPlayerPanel.axaml.cs">
      <DependentUpon>SoundPlayerPanel.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Dialogs\ProjectSettingsDialog.axaml.cs">
      <DependentUpon>ProjectSettingsDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\SearchDialog.axaml.cs">
      <DependentUpon>SearchDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\ItemReferencesDialog.axaml.cs">
      <DependentUpon>ItemReferencesDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Editors\SaveEditorView.axaml.cs">
      <DependentUpon>SaveEditorView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Assets\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\Editors\ScenarioCommandEditors\ScenarioCommandEditorView.axaml.cs">
      <DependentUpon>ScenarioCommandEditorView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Assets\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <PublicClass>true</PublicClass>
      <StronglyTypedFileName>Assets\Strings.Designer.cs</StronglyTypedFileName>
      <StronglyTypedLanguage>CSharp</StronglyTypedLanguage>
      <StronglyTypedNamespace>SerialLoops.Assets</StronglyTypedNamespace>
      <StronglyTypedClassName>Strings</StronglyTypedClassName>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="SerialLoops.icns">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
